// Code generated by protoc-gen-go. DO NOT EDIT.
// source: convey.proto

package conveygo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MediaType int32

const (
	MediaType_UNKNOWN MediaType = 0
	// text/plain
	MediaType_TEXT_PLAIN MediaType = 1
)

var MediaType_name = map[int32]string{
	0: "UNKNOWN",
	1: "TEXT_PLAIN",
}

var MediaType_value = map[string]int32{
	"UNKNOWN":    0,
	"TEXT_PLAIN": 1,
}

func (x MediaType) String() string {
	return proto.EnumName(MediaType_name, int32(x))
}

func (MediaType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44db357c6aa8dfc7, []int{0}
}

type Message struct {
	// Record Hash of Message being replied to
	// (empty if first Message in Conversation).
	Previous []byte `protobuf:"bytes,1,opt,name=previous,proto3" json:"previous,omitempty"`
	// Message Content.
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Media Type.
	Type                 MediaType `protobuf:"varint,3,opt,name=type,proto3,enum=convey.MediaType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_44db357c6aa8dfc7, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetPrevious() []byte {
	if m != nil {
		return m.Previous
	}
	return nil
}

func (m *Message) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Message) GetType() MediaType {
	if m != nil {
		return m.Type
	}
	return MediaType_UNKNOWN
}

type Conversation struct {
	// Conversation Topic.
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conversation) Reset()         { *m = Conversation{} }
func (m *Conversation) String() string { return proto.CompactTextString(m) }
func (*Conversation) ProtoMessage()    {}
func (*Conversation) Descriptor() ([]byte, []int) {
	return fileDescriptor_44db357c6aa8dfc7, []int{1}
}

func (m *Conversation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation.Unmarshal(m, b)
}
func (m *Conversation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation.Marshal(b, m, deterministic)
}
func (m *Conversation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation.Merge(m, src)
}
func (m *Conversation) XXX_Size() int {
	return xxx_messageInfo_Conversation.Size(m)
}
func (m *Conversation) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation proto.InternalMessageInfo

func (m *Conversation) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type Listing struct {
	// Conversation Hash.
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// Conversation Cost.
	Cost uint64 `protobuf:"varint,2,opt,name=cost,proto3" json:"cost,omitempty"`
	// Conversation Timestamp.
	Timestamp uint64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Conversation Starter.
	Author string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	// Conversation Topic.
	Topic                string   `protobuf:"bytes,5,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Listing) Reset()         { *m = Listing{} }
func (m *Listing) String() string { return proto.CompactTextString(m) }
func (*Listing) ProtoMessage()    {}
func (*Listing) Descriptor() ([]byte, []int) {
	return fileDescriptor_44db357c6aa8dfc7, []int{2}
}

func (m *Listing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing.Unmarshal(m, b)
}
func (m *Listing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing.Marshal(b, m, deterministic)
}
func (m *Listing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing.Merge(m, src)
}
func (m *Listing) XXX_Size() int {
	return xxx_messageInfo_Listing.Size(m)
}
func (m *Listing) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing.DiscardUnknown(m)
}

var xxx_messageInfo_Listing proto.InternalMessageInfo

func (m *Listing) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Listing) GetCost() uint64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *Listing) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Listing) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Listing) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type Transaction struct {
	// Token Sender.
	// Sender must initiate transation therefore sender must be bcgo.Record.Creator
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// Token Receiver.
	Receiver string `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	// Token Amount.
	Amount               uint64   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_44db357c6aa8dfc7, []int{3}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Transaction) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *Transaction) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterEnum("convey.MediaType", MediaType_name, MediaType_value)
	proto.RegisterType((*Message)(nil), "convey.Message")
	proto.RegisterType((*Conversation)(nil), "convey.Conversation")
	proto.RegisterType((*Listing)(nil), "convey.Listing")
	proto.RegisterType((*Transaction)(nil), "convey.Transaction")
}

func init() { proto.RegisterFile("convey.proto", fileDescriptor_44db357c6aa8dfc7) }

var fileDescriptor_44db357c6aa8dfc7 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x51, 0xcb, 0xd3, 0x30,
	0x14, 0x86, 0xad, 0x76, 0xad, 0x3d, 0x1b, 0x63, 0x06, 0x99, 0x45, 0xbc, 0x18, 0x53, 0x61, 0x78,
	0xd1, 0x81, 0xfe, 0x82, 0x6d, 0x78, 0x21, 0xeb, 0xea, 0x28, 0x95, 0xa9, 0x37, 0x92, 0x65, 0xc7,
	0x36, 0x60, 0x93, 0x92, 0xa4, 0x93, 0x5e, 0xf8, 0xdf, 0xa5, 0x69, 0xbe, 0xed, 0xbb, 0xcb, 0x93,
	0x73, 0xe0, 0x7d, 0x78, 0x0f, 0x4c, 0x98, 0x14, 0x57, 0xec, 0x92, 0x46, 0x49, 0x23, 0x49, 0x30,
	0xd0, 0xf2, 0x37, 0x84, 0x07, 0xd4, 0x9a, 0x96, 0x48, 0x5e, 0xc3, 0xf3, 0x46, 0xe1, 0x95, 0xcb,
	0x56, 0xc7, 0xde, 0xc2, 0x5b, 0x4d, 0xf2, 0x1b, 0x93, 0x18, 0x42, 0x26, 0x85, 0x41, 0x61, 0xe2,
	0xa7, 0x76, 0xf4, 0x80, 0xe4, 0x3d, 0xf8, 0xa6, 0x6b, 0x30, 0x7e, 0xb6, 0xf0, 0x56, 0xd3, 0x8f,
	0x2f, 0x12, 0x97, 0x72, 0xc0, 0x0b, 0xa7, 0x45, 0xd7, 0x60, 0x6e, 0xc7, 0xcb, 0x77, 0x30, 0xd9,
	0xf5, 0x13, 0xa5, 0xa9, 0xe1, 0x52, 0x90, 0x97, 0x30, 0x32, 0xb2, 0xe1, 0xcc, 0x26, 0x45, 0xf9,
	0x00, 0xcb, 0x7f, 0x10, 0xa6, 0x5c, 0x1b, 0x2e, 0x4a, 0x42, 0xc0, 0xaf, 0xa8, 0xae, 0x9c, 0x89,
	0x7d, 0xf7, 0x7f, 0x4c, 0xea, 0x41, 0xc1, 0xcf, 0xed, 0x9b, 0xbc, 0x81, 0xc8, 0xf0, 0x1a, 0xb5,
	0xa1, 0x75, 0x63, 0x25, 0xfc, 0xfc, 0xfe, 0x41, 0xe6, 0x10, 0xd0, 0xd6, 0x54, 0x52, 0xc5, 0xbe,
	0xcd, 0x71, 0x74, 0x8f, 0x1f, 0x3d, 0x8e, 0xff, 0x01, 0xe3, 0x42, 0x51, 0xa1, 0x29, 0xb3, 0x8e,
	0x73, 0x08, 0x34, 0x8a, 0x0b, 0x2a, 0x27, 0xe9, 0xa8, 0x2f, 0x4a, 0x21, 0x43, 0x7e, 0x45, 0x65,
	0x55, 0xa2, 0xfc, 0xc6, 0x36, 0xb0, 0x96, 0xad, 0x30, 0xce, 0xc5, 0xd1, 0x87, 0x15, 0x44, 0xb7,
	0x4a, 0xc8, 0x18, 0xc2, 0x6f, 0xd9, 0x3e, 0xfb, 0x7a, 0xca, 0x66, 0x4f, 0xc8, 0x14, 0xa0, 0xf8,
	0xfc, 0xbd, 0xf8, 0x75, 0x4c, 0x37, 0x5f, 0xb2, 0x99, 0xb7, 0xdd, 0xc3, 0x2b, 0x26, 0xeb, 0x84,
	0xfe, 0x41, 0x53, 0x21, 0xa7, 0x7f, 0xa9, 0x42, 0x57, 0xea, 0x76, 0x6c, 0x2b, 0xec, 0x8e, 0xfd,
	0x05, 0x7f, 0xbe, 0x2d, 0xb9, 0xa9, 0xda, 0x73, 0xc2, 0x64, 0xbd, 0xde, 0xb8, 0xe5, 0x13, 0x55,
	0x98, 0xa6, 0xbb, 0xf5, 0xb0, 0x5f, 0xca, 0x73, 0x60, 0xaf, 0xfd, 0xe9, 0x7f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x59, 0xd6, 0xa2, 0xa3, 0xfd, 0x01, 0x00, 0x00,
}
